import Head from 'next/head'
import { useEffect, useRef } from 'react'
import styles from '../styles/Home.module.css'
import { Game } from './components/game';

export default function Home() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const soundPopRef = useRef<HTMLAudioElement>(null);
  const soundBubbleSingleRef = useRef<HTMLAudioElement>(null);
  let game: Game | null = null;

  useEffect(() => {
    if (canvasRef.current && !game && soundPopRef.current && soundBubbleSingleRef.current) {
      game = new Game(canvasRef.current, {bubble: {sounds: [soundPopRef.current, soundBubbleSingleRef.current]}});
      game.attachInput();
      game.loop();
    }
  }, [canvasRef, game, soundPopRef]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-black text-lg'>html 2D game template</h1>
        <audio ref={soundPopRef} src="/sounds/pop.ogg"/>
        <audio ref={soundBubbleSingleRef} src="/sounds/bubbles-single1.wav"/>
        <img src="/fish/__cartoon_fish_06_red_idle.png" id="fish-idle-left" className="hidden"/>
        <img src="/fish/__cartoon_fish_06_red_idle_flipped.png" id="fish-idle-right" className="hidden"/>
        <img src="/backdrop.png" id="backdrop" className="hidden"/>
        <canvas ref={canvasRef} className={styles.canvas}></canvas>
      </main>
    </div>
  )
}
