import Head from 'next/head'
import { useEffect, useRef } from 'react'
import styles from '../styles/Home.module.css'
import { Game } from './components/game';

export default function Home() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  let game: Game | null = null;

  useEffect(() => {
    if (canvasRef.current && !game) {
      game = new Game(canvasRef.current);
      game.loop();
    }
  }, [canvasRef, game]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-black text-lg'>html 2D game template</h1>
        <canvas ref={canvasRef} className={styles.canvas}></canvas>
      </main>
    </div>
  )
}
